### ISSUE TITLE
For automotive ver

### ISSUE THREAD

**Issue by yu0411** [techmaved/MediaBrowser-for-Spotify#61]
Hi!
I’m currently using this app on automotive, but I’m encountering the following issue. Do you have any solutions? Thank you.
![截圖 2024-08-16 下午6 11 35](https://github.com/user-attachments/assets/de8a8e21-95e5-40ac-ad70-73f0285e116a)

**Comment by techmaved** [comment]
Hi. This app is not ready to be used by everyone. You need to make changes to use it yourself. Please follow [this](https://developer.spotify.com/documentation/android/tutorials/getting-started#register-your-app) guide and change [this](https://github.com/techmaved/MediaBrowser-for-Spotify/blob/develop/app/build.gradle.kts#L45) line to match your own spotify client id.

Currently I haven't used the app on Android Automotive.
If you have trouble please don't hesitate to ask.
