### ISSUE TITLE
Play controller not displaying after selecting a song

### ISSUE THREAD

**Issue by yangzhewei** [techmaved/MediaBrowser-for-Spotify#63]
When I click on a song in the media library, the player does not appear as expected. Instead, I only see a blank screen without the play controller interface. Below is a screenshot of the issue:

![image](https://github.com/user-attachments/assets/a08eeea3-1a99-4da0-93ac-f47fe49c760a)
![image](https://github.com/user-attachments/assets/f068bba7-0077-4617-9c4f-e81a10080b8e)

**Comment by techmaved** [comment]
The app provides only the media library. When you click on an song your Spotify app on your phone or the last active device are playing the song. The app itself doesn't play the music, spotify does.

**Comment by techmaved** [comment]
Maybe I will look into disabling the player or syncing it with the installed spotify app on the device.
